### ISSUE TITLE
Desync in CSV enum

### ISSUE THREAD

**Issue by sdwvit** [azakordonets/fabricator#13]
Enum entries don't correspond to values on some lines, possible bug?
https://github.com/azakordonets/fabricator/blob/master/src/main/java/fabricator/enums/CsvValueCode.java#L19-L26

**Comment by azakordonets** [comment]
Yeah, looks like a bug. I will take a look at it today. 

Thanks.

**Comment by azakordonets** [comment]
Fixed. I will update library later in the evening, but you can build it for yourself already
