### ISSUE TITLE
Expose seed value as parameter

### ISSUE THREAD

**Issue by jettify** [azakordonets/fabricator#14]
This library is very good for testing purposes, but it should add ability to pass seed value in order to have reproducible results. Any plans to add this feature?

**Comment by azakordonets** [comment]
Not at the moment, but it should be easy to do. Would you like to make a pull request ? Otherwise, i could do it somewhere in a month or two. A bit busy right now with other projects.

**Comment by jettify** [comment]
Sorry not this time, I end up using java library javafaker.
