### ISSUE TITLE
Expose Finance and seed Calendar

### ISSUE THREAD

**Issue by petermoore14** [azakordonets/fabricator#15]
Thanks for the great library! One minor thorn that's been causing some trouble for me is the inability to access the Finance class (I need to instantiate each generator so that I can set a constant seed for reproducible results). Would also be nice if Calendar used its Random in conjunction with RandomDate to ensure reproducible results as well.

**Comment by petermoore14** [comment]
Words has a similar issue as well; should have the option to use a predefined Random as the other classes do.

**Comment by azakordonets** [comment]
Yeah, agree, but i'm currently i'm swapped with my main work and don't have time for this project. If you like, you can make a PR and i'll merge it. Sorry about that

**Comment by petermoore14** [comment]
Yes that's not a problem, am happy to make a PR for you to merge. Will have
something for you shortly.

Thanks,

-Peter

**Comment by azakordonets** [comment]
Thanks a lot. I will check it and try to merge on this weekends

**Comment by azakordonets** [comment]
Thanks for the input again - i have made a new version of the library and pushed it to maven and bintray.
