### ISSUE TITLE
Exception with Play Framework 2.5

### ISSUE THREAD

**Issue by Eluinhost** [azakordonets/fabricator#17]
Attempting to use on Play 2.5.9, and I'm getting the following error:

`java.lang.NoSuchMethodError: play.api.libs.json.JsValue.$bslash$bslash(Ljava/lang/String;)Lscala/collection/Seq;`

Linking to the line https://github.com/azakordonets/fabricator/blob/master/src/main/scala/fabricator/UtilityService.scala#L22

I'm assuming this is due to fabricator having a dependency on `play-json:2.4.0-M2`

**Comment by azakordonets** [comment]
I'll check it out this weekends. Hopefully, on Monday I'll release a new version.

**Comment by azakordonets** [comment]
I have updated play-json version to 2.4.8 , but it looks like this is the version for scala 2.10 version. I'm not sure that it will work with latest Play framework. I have published a new version of the library to maven and bintray - could you check it out and let me know if that works for you ? Not sure how to keep support for both scala 2.10 and 2.11. If it won't work out for you - i'll try to figure out something. if you have any ideas or suggestions - feel free to share them here. 

Thanks.

**Comment by Eluinhost** [comment]
Tested and it is working for scala 2.11.7 using dependency "com.github.azakordonets" %% "fabricator" % "2.1.3"

**Comment by azakordonets** [comment]
Great, thanks :)
