### ISSUE TITLE
Build for scala 2.12

### ISSUE THREAD

**Issue by callicles** [azakordonets/fabricator#25]
Hi!

Your library looks awesome, however I am using scala 2.12 for my project.
Could we get a published build for that scala version?

Thank you

**Comment by azakordonets** [comment]
I'll try to add it support for 2.12 this week

**Comment by azakordonets** [comment]
Tried previous week to add 2.12 scala support and it appears not that easy as i thought it would be . I think i might have to drop 2.10 support for this. It will take a bit longer, sorry

**Comment by callicles** [comment]
ok, thx :)

**Comment by azakordonets** [comment]
@callicles ok, i have just published new version of the library for scala 2.12. Try it out and let me know how it works for you

**Comment by callicles** [comment]
thx! will do
