### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by hamroune** [azakordonets/fabricator#31]
Is it possible to add a custom enumeration for a specific column?

**Comment by azakordonets** [comment]
@hamroune sorry for a late reply - can you be more specific ? Maybe you could give an example of what do you want to achieve ?

**Comment by hamroune** [comment]
let say we have this Enum: FruitEnum ( "Banana", "Apple", "Orange")
is it possible to have something like this:
```
val myList =  List("Banana",  "Apple", "Orange")
fabricator.choice(myList, 2) // <= choose 2 arbitrary (random) elements from the myList !

```

**Comment by azakordonets** [comment]
@hamroune i don't think you can do that out of the box. But you can implement it yourself quite easy. You create a set and you put random items from your list into that set, until that set is the right size. Just keep in mind corner cases when you try to get number of random elements more then you have in your "choice" list. Feel free to make MR for this feature, if you want :)
