### ISSUE TITLE
Build for Scala 2.13

### ISSUE THREAD

**Issue by aartajew** [azakordonets/fabricator#47]
Hi,

We use your awesome library since 5 years for our Gatling performance tests. They've updated Gatling to use Scala 2.13.4. Could you publish a build of your lib for Scala 2.13.4 please?

Thanks in advance :)

**Comment by azakordonets** [comment]
Wow, didn't know that this library is still in use :) I will try to get my rusty scala knowledge back to me and will work on it somewhere this weekends most probably. If you have time, i would love to see your PR for this as well.

**Comment by aartajew** [comment]
Are you kidding? Fabricator is awesome!

**Comment by azakordonets** [comment]
@aartajew thanks for kind words and super sorry that i haven't done the update yet - i have a quite a lot right now on my plane altogether with corona lockdown and curfew we have in Amsterdam.

**Comment by aartajew** [comment]
Ok, no problem, take care! 😄

**Comment by aartajew** [comment]
Hi @azakordonets! Any news on the build? 😄

**Comment by azakordonets** [comment]
Sorry, i was ill last week. Will be away this weekends, so can't promise that i will have time to do it this week. Will try to find some time next week. 
P.S. I'm very fast with accepting PR's :)

**Comment by aartajew** [comment]
Hi, I've just created PR #48 😄

**Comment by aartajew** [comment]
@azakordonets all tests pass, please review and merge it if it's ok 😄

**Comment by azakordonets** [comment]
@aartajew I have released a new version in Sonatype. I hope it will be available by tomorrow.  Please let me know if you will have troubles downloading it. 
Thanks a lot for contribution!

**Comment by aartajew** [comment]
Great, thanks - I'll check tomorrow! 😄

**Comment by azakordonets** [comment]
Yeap, i can see it now in Sonatype Repository. Closing the ticket - https://search.maven.org/artifact/com.github.azakordonets/fabricator_2.13/2.1.9/jar
