### ISSUE TITLE
Right now there is no reason to create Fabricator instance, you can just use static factory methods

### ISSUE THREAD

**Issue by doom369** [azakordonets/fabricator#8]

**Comment by azakordonets** [comment]
Yeah, this is in my improvements list :)

**Comment by azakordonets** [comment]
Done. I've reimplemented the way modules can be called. In Scala it's done a bit differently from Java. Is that what you meant? :)

**Comment by doom369** [comment]
Yes, exactly, such approach simplify usage. In future you can also overload factory methods  with more params, for instance:

val file = Fabricator.file() // initialize file module
file.image(200,300, "drawing.png") // will create a 200x300 image in the root of the project

could be 

val image = Fabricator.image(200,300, "drawing.png");

This is not necessary right now, but when you will have some usage statistics you can implement that.

**Comment by azakordonets** [comment]
Cool, thanks.
